apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: api
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: localhost:5000/flask-app:5
          ports:
            - containerPort: 3000