apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: api
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
  type: NodePort
